In [1]:
import pandas as pd
import numpy as np

In [4]:
data= pd.read_csv('data.csv')

In [6]:
data = data.dropna(axis=0, how='any')
data

,NO. PEDIDO,FECHA,ESCUELA,TANDA,CICLO,NOMBRE COMPLETO,SIZE,CANT,CURSO,SECCION,PRECIO,PAGO
0,1.0,9/27/2021,SAN VICENTE DE PAUL,MATUTINA,PRIMARIA,JONAS GUZMAN,10,1.0,1RO,A,300.0,300.0
1,1.0,9/27/2021,SAN VICENTE DE PAUL,MATUTINA,PRIMARIA,SCARLET JIMENEZ,M,1.0,1RO,A,300.0,300.0
2,1.0,9/27/2021,SAN VICENTE DE PAUL,MATUTINA,PRIMARIA,MICHAEL ABREU,14,1.0,1RO,C,300.0,300.0
3,1.0,9/27/2021,SAN VICENTE DE PAUL,MATUTINA,PRIMARIA,MARCO GARCIA,14,1.0,1RO,D,300.0,300.0
4,1.0,9/27/2021,SAN VICENTE DE PAUL,MATUTINA,PRIMARIA,JESUS GIL,14,1.0,1RO,D,300.0,300.0
...,...,...,...,...,...,...,...,...,...,...,...,...
934,9.0,10/12/2021,LAS MALVINAS,MATUTINA,PRIMARIA,MIRANDA (PROF.CLARA),8,1.0,PP,C,350.0,350.0
935,9.0,10/12/2021,LAS MALVINAS,MATUTINA,PRIMARIA,JUAN JOSE,10,2.0,PP,C,350.0,700.0
936,9.0,10/12/2021,LAS MALVINAS,MATUTINA,PRIMARIA,CAMILA,10,1.0,PP,C,350.0,350.0
937,9.0,10/12/2021,LAS MALVINAS,MATUTINA,PRIMARIA,FRANYELIS,10,1.0,PP,C,350.0,350.0
938,9.0,10/12/2021,LAS MALVINAS,MATUTINA,PRIMARIA,PROF PP C,L,1.0,PP,C,350.0,350.0

In [8]:
producto = pd.read_csv('productos.csv')
size = pd.read_csv('size.csv')
cursos = pd.read_csv('cursos.csv')

In [12]:
data.loc[data.CURSO == 'PP', 'CICLO'] = 'INICIAL'

In [10]:
cursos['Grado'] = cursos.Grado.str.upper()
cursos['Nivel'] = cursos.Nivel.str.upper()
cursos['Tanda'] = cursos.Tanda.str.upper()
cursos

     id_grado_seccion     Grado       Nivel Seccion     Tanda
0                   1        PP     INICIAL       A  MATUTINA
1                   2  MATERNAL     INICIAL       A  MATUTINA
2                   3    KINDER     INICIAL       A  MATUTINA
3                   4       1RO    PRIMARIA       A  MATUTINA
4                   5       2DO    PRIMARIA       A  MATUTINA
..                ...       ...         ...     ...       ...
310               311       2DO  SECUNDARIA       G       JEE
311               312       3RO  SECUNDARIA       G       JEE
312               313       4TO  SECUNDARIA       G       JEE
313               314       5TO  SECUNDARIA       G       JEE
314               315       6TO  SECUNDARIA       G       JEE

[315 rows x 5 columns]

In [21]:
cursos.columns

Index(['id_grado_seccion', 'Grado', 'Nivel', 'Seccion', 'Tanda'], dtype='object')

In [14]:
data.columns

Index(['NO. PEDIDO', 'FECHA', 'ESCUELA', 'TANDA', 'CICLO', 'NOMBRE COMPLETO',
       'SIZE', 'CANT', 'CURSO', 'SECCION ', 'PRECIO', 'PAGO'],
      dtype='object')

In [16]:
id_grado = data.loc[:,['CURSO', 'CICLO', 'SECCION ', 'TANDA']]

In [31]:
for x in id_grado.values:
    print(cursos.loc[x,'gr' )
        &(cursos.Nivel == x )&(cursos.Seccion == x[2] )&(cursos.Tanda == x[3] )
,'id_grado_seccion'])

ValueError: ('Lengths must match to compare', (315,), (4,))

In [30]:
for i in id_grado.values:
    print(i)

['1RO' 'PRIMARIA' 'A' 'MATUTINA']
['1RO' 'PRIMARIA' 'A' 'MATUTINA']
['1RO' 'PRIMARIA' 'C' 'MATUTINA']
['1RO' 'PRIMARIA' 'D' 'MATUTINA']
['1RO' 'PRIMARIA' 'D' 'MATUTINA']
['1RO' 'PRIMARIA' 'E' 'MATUTINA']
['1RO' 'PRIMARIA' 'E' 'MATUTINA']
['2DO' 'PRIMARIA' 'A' 'MATUTINA']
['2DO' 'PRIMARIA' 'A' 'MATUTINA']
['2DO' 'PRIMARIA' 'C' 'MATUTINA']
['2DO' 'PRIMARIA' 'C' 'MATUTINA']
['3RO' 'PRIMARIA' 'C' 'MATUTINA']
['3RO' 'PRIMARIA' 'C' 'MATUTINA']
['3RO' 'PRIMARIA' 'D' 'MATUTINA']
['4TO' 'PRIMARIA' 'A' 'MATUTINA']
['4TO' 'PRIMARIA' 'B' 'MATUTINA']
['4TO' 'PRIMARIA' 'B' 'MATUTINA']
['4TO' 'PRIMARIA' 'D' 'MATUTINA']
['4TO' 'PRIMARIA' 'D' 'MATUTINA']
['4TO' 'PRIMARIA' 'D' 'MATUTINA']
['5TO' 'PRIMARIA' 'A' 'MATUTINA']
['5TO' 'PRIMARIA' 'B' 'MATUTINA']
['5TO' 'PRIMARIA' 'C' 'MATUTINA']
['5TO' 'PRIMARIA' 'C' 'MATUTINA']
['5TO' 'PRIMARIA' 'D' 'MATUTINA']
['6TO' 'PRIMARIA' 'A' 'MATUTINA']
['6TO' 'PRIMARIA' 'A' 'MATUTINA']
['6TO' 'PRIMARIA' 'C' 'MATUTINA']
['6TO' 'PRIMARIA' 'C' 'MATUTINA']
['6TO' 'PRIMARIA' 'C' 'MATUTINA']
['5TO' 'SECUNDARIA' 'B' 'MATUTINA']
['1RO' 'PRIMARIA' 'A' 'MATUTINA']
['1RO' 'PRIMARIA' 'A' 'MATUTINA']
['1RO' 'PRIMARIA' 'A' 'MATUTINA']
['1RO' 'PRIMARIA' 'A' 'MATUTINA']
['1RO' 'PRIMARIA' 'B' 'MATUTINA']
['1RO' 'PRIMARIA' 'B' 'MATUTINA']
['1RO' 'PRIMARIA' 'B' 'MATUTINA']
['1RO' 'PRIMARIA' 'B' 'MATUTINA']
['1RO' 'PRIMARIA' 'B' 'MATUTINA']
['1RO' 'PRIMARIA' 'B' 'MATUTINA']
['1RO' 'PRIMARIA' 'C' 'MATUTINA']
['1RO' 'PRIMARIA' 'C' 'MATUTINA']
['1RO' 'PRIMARIA' 'C' 'MATUTINA']
['1RO' 'PRIMARIA' 'D' 'MATUTINA']
['1RO' 'PRIMARIA' 'D' 'MATUTINA']
['1RO' 'PRIMARIA' 'E' 'MATUTINA']
['1RO' 'PRIMARIA' 'E' 'MATUTINA']
['1RO' 'PRIMARIA' 'E' 'MATUTINA']
['1RO' 'PRIMARIA' 'E' 'MATUTINA']
['1RO' 'PRIMARIA' 'E' 'MATUTINA']
['2DO' 'PRIMARIA' 'A' 'MATUTINA']
['2DO' 'PRIMARIA' 'A' 'MATUTINA']
['2DO' 'PRIMARIA' 'A' 'MATUTINA']
['2DO' 'PRIMARIA' 'B' 'MATUTINA']
['2DO' 'PRIMARIA' 'B' 'MATUTINA']
['2DO' 'PRIMARIA' 'B' 'MATUTINA']
['2DO' 'PRIMARIA' 'B' 'MATUTINA']
['2DO' 'PRIMARIA' 'C' 'MATUTINA']
['2DO' 'PRIMARIA' 'C' 'MATUTINA']
['2DO' 'PRIMARIA' 'C' 'MATUTINA']
['2DO' 'PRIMARIA' 'C' 'MATUTINA']
['2DO' 'PRIMARIA' 'C' 'MATUTINA']
['2DO' 'PRIMARIA' 'C' 'MATUTINA']
['2DO' 'PRIMARIA' 'C' 'MATUTINA']
['2DO' 'PRIMARIA' 'C' 'MATUTINA']
['2DO' 'PRIMARIA' 'C' 'MATUTINA']
['2DO' 'PRIMARIA' 'D' 'MATUTINA']
['2DO' 'PRIMARIA' 'D' 'MATUTINA']
['2DO' 'PRIMARIA' 'D' 'MATUTINA']
['2DO' 'PRIMARIA' 'D' 'MATUTINA']
['2DO' 'PRIMARIA' 'D' 'MATUTINA']
['2DO' 'PRIMARIA' 'E' 'MATUTINA']
['3RO' 'PRIMARIA' 'A' 'MATUTINA']
['3RO' 'PRIMARIA' 'A' 'MATUTINA']
['3RO' 'PRIMARIA' 'A' 'MATUTINA']
['3RO' 'PRIMARIA' 'A' 'MATUTINA']
['3RO' 'PRIMARIA' 'A' 'MATUTINA']
['3RO' 'PRIMARIA' 'B' 'MATUTINA']
['3RO' 'PRIMARIA' 'B' 'MATUTINA']
['3RO' 'PRIMARIA' 'B' 'MATUTINA']
['3RO' 'PRIMARIA' 'B' 'MATUTINA']
['3RO' 'PRIMARIA' 'B' 'MATUTINA']
['3RO' 'PRIMARIA' 'B' 'MATUTINA']
['3RO' 'PRIMARIA' 'B' 'MATUTINA']
['3RO' 'PRIMARIA' 'C' 'MATUTINA']
['3RO' 'PRIMARIA' 'C' 'MATUTINA']
['3RO' 'PRIMARIA' 'C' 'MATUTINA']
['3RO' 'PRIMARIA' 'C' 'MATUTINA']
['3RO' 'PRIMARIA' 'C' 'MATUTINA']
['3RO' 'PRIMARIA' 'D' 'MATUTINA']
['3RO' 'PRIMARIA' 'D' 'MATUTINA']
['3RO' 'PRIMARIA' 'D' 'MATUTINA']
['3RO' 'PRIMARIA' 'D' 'MATUTINA']
['3RO' 'PRIMARIA' 'D' 'MATUTINA']
['3RO' 'PRIMARIA' 'D' 'MATUTINA']
['3RO' 'PRIMARIA' 'D' 'MATUTINA']
['3RO' 'PRIMARIA' 'D' 'MATUTINA']
['3RO' 'PRIMARIA' 'D' 'MATUTINA']
['4TO' 'PRIMARIA' 'A' 'MATUTINA']
['4TO' 'PRIMARIA' 'A' 'MATUTINA']
['4TO' 'PRIMARIA' 'A' 'MATUTINA']
['4TO' 'PRIMARIA' 'A' 'MATUTINA']
['4TO' 'PRIMARIA' 'A' 'MATUTINA']
['4TO' 'PRIMARIA' 'A' 'MATUTINA']
['4TO' 'PRIMARIA' 'A' 'MATUTINA']
['4TO' 'PRIMARIA' 'A' 'MATUTINA']
['4TO' 'PRIMARIA' 'B' 'MATUTINA']
['4TO' 'PRIMARIA' 'B' 'MATUTINA']
['4TO' 'PRIMARIA' 'B' 'MATUTINA']
['4TO' 'PRIMARIA' 'B' 'MATUTINA']
['4TO' 'PRIMARIA' 'B' 'MATUTINA']
['4TO' 'PRIMARIA' 'B' 'MATUTINA']
['4TO' 'PRIMARIA' 'B' 'MATUTINA']
['4TO' 'PRIMARIA' 'B' 'MATUTINA']
['4TO' 'PRIMARIA' 'B' 'MATUTINA']
['4TO' 'PRIMARIA' 'C' 'MATUTINA']
['4TO' 'PRIMARIA' 'C' 'MATUTINA']
['4TO' 'PRIMARIA' 'C' 'MATUTINA']
['4TO' 'PRIMARIA' 'C' 'MATUTINA']
['4TO' 'PRIMARIA' 'D' 'MATUTINA']
['4TO' 'PRIMARIA' 'D' 'MATUTINA']
['4TO' 'PRIMARIA' 'D' 'MATUTINA']
['4TO' 'PRIMARIA' 'D' 'MATUTINA']
['4TO' 'PRIMARIA' 'D' 'MATUTINA']
['5TO' 'PRIMARIA' 'A' 'MATUTINA']
['5TO' 'PRIMARIA' 'A' 'MATUTINA']
['5TO' 'PRIMARIA' 'B' 'MATUTINA']
['5TO' 'PRIMARIA' 'B' 'MATUTINA']
['5TO' 'PRIMARIA' 'B' 'MATUTINA']
['5TO' 'PRIMARIA' 'B' 'MATUTINA']
['5TO' 'PRIMARIA' 'C' 'MATUTINA']
['5TO' 'PRIMARIA' 'C' 'MATUTINA']
['5TO' 'PRIMARIA' 'C' 'MATUTINA']
['5TO' 'PRIMARIA' 'C' 'MATUTINA']
['5TO' 'PRIMARIA' 'C' 'MATUTINA']
['5TO' 'PRIMARIA' 'C' 'MATUTINA']
['5TO' 'PRIMARIA' 'D' 'MATUTINA']
['5TO' 'PRIMARIA' 'D' 'MATUTINA']
['5TO' 'PRIMARIA' 'D' 'MATUTINA']
['5TO' 'PRIMARIA' 'D' 'MATUTINA']
['5TO' 'PRIMARIA' 'D' 'MATUTINA']
['6TO' 'PRIMARIA' 'A' 'MATUTINA']
['6TO' 'PRIMARIA' 'A' 'MATUTINA']
['6TO' 'PRIMARIA' 'A' 'MATUTINA']
['6TO' 'PRIMARIA' 'A' 'MATUTINA']
['6TO' 'PRIMARIA' 'A' 'MATUTINA']
['6TO' 'PRIMARIA' 'A' 'MATUTINA']
['6TO' 'PRIMARIA' 'A' 'MATUTINA']
['6TO' 'PRIMARIA' 'A' 'MATUTINA']
['6TO' 'PRIMARIA' 'A' 'MATUTINA']
['6TO' 'PRIMARIA' 'B' 'MATUTINA']
['6TO' 'PRIMARIA' 'B' 'MATUTINA']
['6TO' 'PRIMARIA' 'B' 'MATUTINA']
['6TO' 'PRIMARIA' 'B' 'MATUTINA']
['6TO' 'PRIMARIA' 'B' 'MATUTINA']
['6TO' 'PRIMARIA' 'B' 'MATUTINA']
['6TO' 'PRIMARIA' 'B' 'MATUTINA']
['6TO' 'PRIMARIA' 'B' 'MATUTINA']
['6TO' 'PRIMARIA' 'B' 'MATUTINA']
['6TO' 'PRIMARIA' 'C' 'MATUTINA']
['6TO' 'PRIMARIA' 'C' 'MATUTINA']
['6TO' 'PRIMARIA' 'C' 'MATUTINA']
['6TO' 'PRIMARIA' 'C' 'MATUTINA']
['6TO' 'PRIMARIA' 'C' 'MATUTINA']
['6TO' 'PRIMARIA' 'C' 'MATUTINA']
['6TO' 'PRIMARIA' 'C' 'MATUTINA']
['6TO' 'PRIMARIA' 'C' 'MATUTINA']
['6TO' 'PRIMARIA' 'C' 'MATUTINA']
['6TO' 'PRIMARIA' 'C' 'MATUTINA']
['6TO' 'PRIMARIA' 'C' 'MATUTINA']
['6TO' 'PRIMARIA' 'D' 'MATUTINA']
['6TO' 'PRIMARIA' 'D' 'MATUTINA']
['PP' 'INICIAL' 'A' 'MATUTINA']
['PP' 'INICIAL' 'A' 'MATUTINA']
['PP' 'INICIAL' 'A' 'MATUTINA']
['PP' 'INICIAL' 'A' 'MATUTINA']
['PP' 'INICIAL' 'B' 'MATUTINA']
['PP' 'INICIAL' 'C' 'MATUTINA']
['PP' 'INICIAL' 'C' 'MATUTINA']
['1RO' 'SECUNDARIA' 'B' 'MATUTINA']
['1RO' 'SECUNDARIA' 'B' 'MATUTINA']
['1RO' 'SECUNDARIA' 'B' 'MATUTINA']
['1RO' 'SECUNDARIA' 'B' 'MATUTINA']
['2DO' 'SECUNDARIA' 'A' 'MATUTINA']
['2DO' 'SECUNDARIA' 'C' 'MATUTINA']
['2DO' 'SECUNDARIA' 'D' 'MATUTINA']
['3RO' 'SECUNDARIA' 'B' 'MATUTINA']
['3RO' 'SECUNDARIA' 'C' 'MATUTINA']
['3RO' 'SECUNDARIA' 'D' 'MATUTINA']
['4TO' 'SECUNDARIA' 'A' 'MATUTINA']
['4TO' 'SECUNDARIA' 'A' 'MATUTINA']
['4TO' 'SECUNDARIA' 'A' 'MATUTINA']
['4TO' 'SECUNDARIA' 'A' 'MATUTINA']
['4TO' 'SECUNDARIA' 'A' 'MATUTINA']
['4TO' 'SECUNDARIA' 'A' 'MATUTINA']
['4TO' 'SECUNDARIA' 'B' 'MATUTINA']
['4TO' 'SECUNDARIA' 'B' 'MATUTINA']
['4TO' 'SECUNDARIA' 'B' 'MATUTINA']
['4TO' 'SECUNDARIA' 'B' 'MATUTINA']
['4TO' 'SECUNDARIA' 'C' 'MATUTINA']
['4TO' 'SECUNDARIA' 'D' 'MATUTINA']
['4TO' 'SECUNDARIA' 'D' 'MATUTINA']
['4TO' 'SECUNDARIA' 'D' 'MATUTINA']
['4TO' 'SECUNDARIA' 'D' 'MATUTINA']
['6TO' 'SECUNDARIA' 'C' 'MATUTINA']
['2DO' 'PRIMARIA' 'A' 'MATUTINA']
['3RO' 'PRIMARIA' 'A' 'MATUTINA']
['3RO' 'PRIMARIA' 'B' 'MATUTINA']
['4TO' 'PRIMARIA' 'A' 'MATUTINA']
['4TO' 'PRIMARIA' 'A' 'MATUTINA']
['5TO' 'PRIMARIA' 'A' 'MATUTINA']
['5TO' 'PRIMARIA' 'A' 'MATUTINA']
['6TO' 'PRIMARIA' 'A' 'MATUTINA']
['6TO' 'PRIMARIA' 'A' 'MATUTINA']
['6TO' 'PRIMARIA' 'A' 'MATUTINA']
['PP' 'INICIAL' 'A' 'MATUTINA']
['1RO' 'SECUNDARIA' 'A' 'MATUTINA']
['1RO' 'SECUNDARIA' 'A' 'MATUTINA']
['1RO' 'SECUNDARIA' 'B' 'MATUTINA']
['2DO' 'SECUNDARIA' 'A' 'MATUTINA']
['2DO' 'SECUNDARIA' 'A' 'MATUTINA']
['2DO' 'SECUNDARIA' 'A' 'MATUTINA']
['2DO' 'PRIMARIA' 'A' 'VESPERTINA']
['2DO' 'PRIMARIA' 'A' 'VESPERTINA']
['3RO' 'PRIMARIA' 'A' 'VESPERTINA']
['3RO' 'PRIMARIA' 'A' 'VESPERTINA']
['4TO' 'PRIMARIA' 'A' 'VESPERTINA']
['5TO' 'PRIMARIA' 'B' 'VESPERTINA']
['5TO' 'PRIMARIA' 'A' 'VESPERTINA']
['6TO' 'PRIMARIA' 'A' 'VESPERTINA']
['6TO' 'PRIMARIA' 'B' 'VESPERTINA']
['PP' 'INICIAL' 'B' 'VESPERTINA']
['1RO' 'SECUNDARIA' 'B' 'VESPERTINA']
['1RO' 'SECUNDARIA' 'B' 'VESPERTINA']
['2DO' 'SECUNDARIA' 'B' 'VESPERTINA']
['1RO' 'PRIMARIA' 'A' 'MATUTINA']
['1RO' 'PRIMARIA' 'A' 'MATUTINA']
['1RO' 'PRIMARIA' 'A' 'MATUTINA']
['2DO' 'PRIMARIA' 'A' 'MATUTINA']
['2DO' 'PRIMARIA' 'B' 'MATUTINA']
['3RO' 'PRIMARIA' 'A' 'MATUTINA']
['3RO' 'PRIMARIA' 'B' 'MATUTINA']
['3RO' 'PRIMARIA' 'B' 'MATUTINA']
['4TO' 'PRIMARIA' 'A' 'MATUTINA']
['4TO' 'PRIMARIA' 'B' 'MATUTINA']
['6TO' 'PRIMARIA' 'A' 'MATUTINA']
['2DO' 'SECUNDARIA' 'B' 'MATUTINA']
['2DO' 'SECUNDARIA' 'B' 'MATUTINA']
['2DO' 'SECUNDARIA' 'B' 'MATUTINA']
['5TO' 'PRIMARIA' 'B' 'VESPERTINA']
['6TO' 'PRIMARIA' 'A' 'VESPERTINA']
['6TO' 'PRIMARIA' 'B' 'VESPERTINA']
['6TO' 'PRIMARIA' 'B' 'VESPERTINA']
['1RO' 'SECUNDARIA' 'B' 'VESPERTINA']
['1RO' 'SECUNDARIA' 'B' 'VESPERTINA']
['1RO' 'SECUNDARIA' 'B' 'VESPERTINA']
['2DO' 'SECUNDARIA' 'C' 'VESPERTINA']
['1RO' 'PRIMARIA' 'A' 'MATUTINA']
['1RO' 'PRIMARIA' 'A' 'MATUTINA']
['1RO' 'PRIMARIA' 'A' 'MATUTINA']
['1RO' 'PRIMARIA' 'A' 'MATUTINA']
['1RO' 'PRIMARIA' 'A' 'MATUTINA']
['1RO' 'PRIMARIA' 'A' 'MATUTINA']
['1RO' 'PRIMARIA' 'A' 'MATUTINA']
['1RO' 'PRIMARIA' 'A' 'MATUTINA']
['1RO' 'PRIMARIA' 'A' 'MATUTINA']
['1RO' 'PRIMARIA' 'B' 'MATUTINA']
['1RO' 'PRIMARIA' 'B' 'MATUTINA']
['1RO' 'PRIMARIA' 'B' 'MATUTINA']
['1RO' 'PRIMARIA' 'B' 'MATUTINA']
['1RO' 'PRIMARIA' 'B' 'MATUTINA']
['1RO' 'PRIMARIA' 'B' 'MATUTINA']
['1RO' 'PRIMARIA' 'B' 'MATUTINA']
['1RO' 'PRIMARIA' 'B' 'MATUTINA']
['1RO' 'PRIMARIA' 'B' 'MATUTINA']
['1RO' 'PRIMARIA' 'B' 'MATUTINA']
['2DO' 'PRIMARIA' 'A' 'MATUTINA']
['2DO' 'PRIMARIA' 'A' 'MATUTINA']
['2DO' 'PRIMARIA' 'A' 'MATUTINA']
['2DO' 'PRIMARIA' 'A' 'MATUTINA']
['2DO' 'PRIMARIA' 'A' 'MATUTINA']
['2DO' 'PRIMARIA' 'A' 'MATUTINA']
['2DO' 'PRIMARIA' 'A' 'MATUTINA']
['2DO' 'PRIMARIA' 'A' 'MATUTINA']
['2DO' 'PRIMARIA' 'A' 'MATUTINA']
['2DO' 'PRIMARIA' 'A' 'MATUTINA']
['3RO' 'PRIMARIA' 'A' 'MATUTINA']
['3RO' 'PRIMARIA' 'A' 'MATUTINA']
['3RO' 'PRIMARIA' 'A' 'MATUTINA']
['3RO' 'PRIMARIA' 'A' 'MATUTINA']
['3RO' 'PRIMARIA' 'A' 'MATUTINA']
['3RO' 'PRIMARIA' 'A' 'MATUTINA']
['3RO' 'PRIMARIA' 'A' 'MATUTINA']
['3RO' 'PRIMARIA' 'A' 'MATUTINA']
['3RO' 'PRIMARIA' 'A' 'MATUTINA']
['3RO' 'PRIMARIA' 'A' 'MATUTINA']
['3RO' 'PRIMARIA' 'A' 'MATUTINA']
['3RO' 'PRIMARIA' 'A' 'MATUTINA']
['3RO' 'PRIMARIA' 'A' 'MATUTINA']
['3RO' 'PRIMARIA' 'A' 'MATUTINA']
['3RO' 'PRIMARIA' 'A' 'MATUTINA']
['3RO' 'PRIMARIA' 'A' 'MATUTINA']
['3RO' 'PRIMARIA' 'A' 'MATUTINA']
['3RO' 'PRIMARIA' 'B' 'MATUTINA']
['3RO' 'PRIMARIA' 'B' 'MATUTINA']
['3RO' 'PRIMARIA' 'B' 'MATUTINA']
['3RO' 'PRIMARIA' 'B' 'MATUTINA']
['3RO' 'PRIMARIA' 'B' 'MATUTINA']
['3RO' 'PRIMARIA' 'B' 'MATUTINA']
['3RO' 'PRIMARIA' 'B' 'MATUTINA']
['3RO' 'PRIMARIA' 'B' 'MATUTINA']
['4TO' 'PRIMARIA' 'A' 'MATUTINA']
['4TO' 'PRIMARIA' 'A' 'MATUTINA']
['4TO' 'PRIMARIA' 'A' 'MATUTINA']
['4TO' 'PRIMARIA' 'A' 'MATUTINA']
['4TO' 'PRIMARIA' 'A' 'MATUTINA']
['4TO' 'PRIMARIA' 'A' 'MATUTINA']
['4TO' 'PRIMARIA' 'A' 'MATUTINA']
['4TO' 'PRIMARIA' 'B' 'MATUTINA']
['4TO' 'PRIMARIA' 'B' 'MATUTINA']
['4TO' 'PRIMARIA' 'B' 'MATUTINA']
['4TO' 'PRIMARIA' 'B' 'MATUTINA']
['4TO' 'PRIMARIA' 'B' 'MATUTINA']
['4TO' 'PRIMARIA' 'B' 'MATUTINA']
['4TO' 'PRIMARIA' 'B' 'MATUTINA']
['5TO' 'PRIMARIA' 'A' 'MATUTINA']
['5TO' 'PRIMARIA' 'A' 'MATUTINA']
['5TO' 'PRIMARIA' 'A' 'MATUTINA']
['5TO' 'PRIMARIA' 'A' 'MATUTINA']
['5TO' 'PRIMARIA' 'A' 'MATUTINA']
['5TO' 'PRIMARIA' 'A' 'MATUTINA']
['5TO' 'PRIMARIA' 'A' 'MATUTINA']
['5TO' 'PRIMARIA' 'A' 'MATUTINA']
['5TO' 'PRIMARIA' 'A' 'MATUTINA']
['5TO' 'PRIMARIA' 'B' 'MATUTINA']
['5TO' 'PRIMARIA' 'B' 'MATUTINA']
['5TO' 'PRIMARIA' 'B' 'MATUTINA']
['5TO' 'PRIMARIA' 'B' 'MATUTINA']
['5TO' 'PRIMARIA' 'B' 'MATUTINA']
['5TO' 'PRIMARIA' 'B' 'MATUTINA']
['6TO' 'PRIMARIA' 'A' 'MATUTINA']
['6TO' 'PRIMARIA' 'A' 'MATUTINA']
['6TO' 'PRIMARIA' 'A' 'MATUTINA']
['6TO' 'PRIMARIA' 'A' 'MATUTINA']
['6TO' 'PRIMARIA' 'A' 'MATUTINA']
['6TO' 'PRIMARIA' 'A' 'MATUTINA']
['6TO' 'PRIMARIA' 'A' 'MATUTINA']
['6TO' 'PRIMARIA' 'A' 'MATUTINA']
['6TO' 'PRIMARIA' 'B' 'MATUTINA']
['6TO' 'PRIMARIA' 'B' 'MATUTINA']
['6TO' 'PRIMARIA' 'B' 'MATUTINA']
['PP' 'INICIAL' 'A' 'MATUTINA']
['PP' 'INICIAL' 'A' 'MATUTINA']
['PP' 'INICIAL' 'A' 'MATUTINA']
['PP' 'INICIAL' 'A' 'MATUTINA']
['PP' 'INICIAL' 'A' 'MATUTINA']
['PP' 'INICIAL' 'A' 'MATUTINA']
['1RO' 'PRIMARIA' 'A' 'MATUTINA']
['1RO' 'PRIMARIA' 'A' 'MATUTINA']
['1RO' 'PRIMARIA' 'B' 'MATUTINA']
['1RO' 'PRIMARIA' 'B' 'MATUTINA']
['1RO' 'PRIMARIA' 'C' 'MATUTINA']
['1RO' 'PRIMARIA' 'D' 'MATUTINA']
['1RO' 'PRIMARIA' 'E' 'MATUTINA']
['2DO' 'PRIMARIA' 'C' 'MATUTINA']
['2DO' 'PRIMARIA' 'E' 'MATUTINA']
['3RO' 'PRIMARIA' 'A' 'MATUTINA']
['4TO' 'PRIMARIA' 'B' 'MATUTINA']
['4TO' 'PRIMARIA' 'B' 'MATUTINA']
['4TO' 'PRIMARIA' 'B' 'MATUTINA']
['4TO' 'PRIMARIA' 'C' 'MATUTINA']
['5TO' 'PRIMARIA' 'A' 'MATUTINA']
['5TO' 'PRIMARIA' 'A' 'MATUTINA']
['5TO' 'PRIMARIA' 'B' 'MATUTINA']
['5TO' 'PRIMARIA' 'C' 'MATUTINA']
['5TO' 'PRIMARIA' 'C' 'MATUTINA']
['PP' 'INICIAL' 'A' 'MATUTINA']
['PP' 'INICIAL' 'A' 'MATUTINA']
['1RO' 'SECUNDARIA' 'A' 'MATUTINA']
['1RO' 'SECUNDARIA' 'B' 'MATUTINA']
['1RO' 'SECUNDARIA' 'C' 'MATUTINA']
['1RO' 'SECUNDARIA' 'D' 'MATUTINA']
['1RO' 'SECUNDARIA' 'D' 'MATUTINA']
['1RO' 'SECUNDARIA' 'D' 'MATUTINA']
['1RO' 'SECUNDARIA' 'D' 'MATUTINA']
['1RO' 'SECUNDARIA' 'A' 'MATUTINA']
['2DO' 'SECUNDARIA' 'A' 'MATUTINA']
['2DO' 'SECUNDARIA' 'C' 'MATUTINA']
['2DO' 'SECUNDARIA' 'D' 'MATUTINA']
['2DO' 'SECUNDARIA' 'D' 'MATUTINA']
['3RO' 'SECUNDARIA' 'B' 'MATUTINA']
['3RO' 'SECUNDARIA' 'B' 'MATUTINA']
['3RO' 'SECUNDARIA' 'B' 'MATUTINA']
['4TO' 'SECUNDARIA' 'B' 'MATUTINA']
['4TO' 'SECUNDARIA' 'B' 'MATUTINA']
['4TO' 'SECUNDARIA' 'B' 'MATUTINA']
['4TO' 'SECUNDARIA' 'B' 'MATUTINA']
['4TO' 'SECUNDARIA' 'B' 'MATUTINA']
['4TO' 'SECUNDARIA' 'B' 'MATUTINA']
['4TO' 'SECUNDARIA' 'C' 'MATUTINA']
['4TO' 'SECUNDARIA' 'D' 'MATUTINA']
['4TO' 'SECUNDARIA' 'D' 'MATUTINA']
['4TO' 'SECUNDARIA' 'D' 'MATUTINA']
['4TO' 'SECUNDARIA' 'D' 'MATUTINA']
['4TO' 'SECUNDARIA' 'D' 'MATUTINA']
['5TO' 'SECUNDARIA' 'A' 'MATUTINA']
['5TO' 'SECUNDARIA' 'B' 'MATUTINA']
['5TO' 'SECUNDARIA' 'C' 'MATUTINA']
['5TO' 'SECUNDARIA' 'C' 'MATUTINA']
['6TO' 'SECUNDARIA' 'A' 'MATUTINA']
['6TO' 'SECUNDARIA' 'B' 'MATUTINA']
['6TO' 'SECUNDARIA' 'B' 'MATUTINA']
['1RO' 'PRIMARIA' 'B' 'VESPERTINA']
['2DO' 'PRIMARIA' 'B' 'VESPERTINA']
['2DO' 'PRIMARIA' 'C' 'VESPERTINA']
['2DO' 'PRIMARIA' 'D' 'VESPERTINA']
['3RO' 'PRIMARIA' 'A' 'VESPERTINA']
['3RO' 'PRIMARIA' 'B' 'VESPERTINA']
['3RO' 'PRIMARIA' 'B' 'VESPERTINA']
['4TO' 'PRIMARIA' 'A' 'VESPERTINA']
['4TO' 'PRIMARIA' 'D' 'VESPERTINA']
['5TO' 'PRIMARIA' 'A' 'VESPERTINA']
['5TO' 'PRIMARIA' 'D' 'VESPERTINA']
['6TO' 'PRIMARIA' 'B' 'VESPERTINA']
['6TO' 'PRIMARIA' 'C' 'VESPERTINA']
['6TO' 'PRIMARIA' 'C' 'VESPERTINA']
['6TO' 'PRIMARIA' 'C' 'VESPERTINA']
['1RO' 'SECUNDARIA' 'B' 'VESPERTINA']
['1RO' 'SECUNDARIA' 'B' 'VESPERTINA']
['1RO' 'SECUNDARIA' 'B' 'VESPERTINA']
['1RO' 'SECUNDARIA' 'B' 'VESPERTINA']
['2DO' 'SECUNDARIA' 'A' 'VESPERTINA']
['2DO' 'SECUNDARIA' 'A' 'VESPERTINA']
['2DO' 'SECUNDARIA' 'D' 'VESPERTINA']
['2DO' 'SECUNDARIA' 'A' 'VESPERTINA']
['3RO' 'SECUNDARIA' 'B' 'VESPERTINA']
['3RO' 'SECUNDARIA' 'B' 'VESPERTINA']
['3RO' 'SECUNDARIA' 'C' 'VESPERTINA']
['4TO' 'SECUNDARIA' 'B' 'VESPERTINA']
['4TO' 'SECUNDARIA' 'B' 'VESPERTINA']
['4TO' 'SECUNDARIA' 'C' 'VESPERTINA']
['4TO' 'SECUNDARIA' 'C' 'VESPERTINA']
['5TO' 'SECUNDARIA' 'A' 'VESPERTINA']
['5TO' 'SECUNDARIA' 'A' 'VESPERTINA']
['5TO' 'SECUNDARIA' 'A' 'VESPERTINA']
['5TO' 'SECUNDARIA' 'C' 'VESPERTINA']
['6TO' 'SECUNDARIA' 'A' 'VESPERTINA']
['6TO' 'SECUNDARIA' 'A' 'VESPERTINA']
['6TO' 'SECUNDARIA' 'B' 'VESPERTINA']
['6TO' 'SECUNDARIA' 'B' 'VESPERTINA']
['3RO' 'PRIMARIA' 'C' 'MATUTINA']
['6TO' 'PRIMARIA' 'A' 'MATUTINA']
['6TO' 'PRIMARIA' 'A' 'MATUTINA']
['6TO' 'PRIMARIA' 'B' 'MATUTINA']
['1RO' 'SECUNDARIA' 'C' 'MATUTINA']
['1RO' 'SECUNDARIA' 'C' 'MATUTINA']
['1RO' 'SECUNDARIA' 'D' 'MATUTINA']
['1RO' 'SECUNDARIA' 'D' 'MATUTINA']
['3RO' 'SECUNDARIA' 'A' 'MATUTINA']
['3RO' 'SECUNDARIA' 'C' 'MATUTINA']
['4TO' 'SECUNDARIA' 'A' 'MATUTINA']
['4TO' 'SECUNDARIA' 'C' 'MATUTINA']
['4TO' 'SECUNDARIA' 'C' 'MATUTINA']
['5TO' 'SECUNDARIA' 'A' 'MATUTINA']
['6TO' 'SECUNDARIA' 'A' 'MATUTINA']
['6TO' 'SECUNDARIA' 'A' 'MATUTINA']
['6TO' 'SECUNDARIA' 'B' 'MATUTINA']
['6TO' 'SECUNDARIA' 'B' 'MATUTINA']
['6TO' 'SECUNDARIA' 'B' 'MATUTINA']
['6TO' 'SECUNDARIA' 'B' 'MATUTINA']
['6TO' 'SECUNDARIA' 'C' 'MATUTINA']
['PP' 'INICIAL' 'A' 'MATUTINA']
['1RO' 'SECUNDARIA' 'A' 'MATUTINA']
['1RO' 'SECUNDARIA' 'A' 'MATUTINA']
['1RO' 'SECUNDARIA' 'A' 'MATUTINA']
['1RO' 'SECUNDARIA' 'B' 'MATUTINA']
['2DO' 'SECUNDARIA' 'A' 'MATUTINA']
['2DO' 'SECUNDARIA' 'A' 'MATUTINA']
['2DO' 'SECUNDARIA' 'A' 'MATUTINA']
['2DO' 'SECUNDARIA' 'B' 'MATUTINA']
['2DO' 'SECUNDARIA' 'B' 'MATUTINA']
['2DO' 'SECUNDARIA' 'C' 'MATUTINA']
['3RO' 'SECUNDARIA' 'C' 'MATUTINA']
['3RO' 'SECUNDARIA' 'C' 'MATUTINA']
['3RO' 'SECUNDARIA' 'D' 'MATUTINA']
['3RO' 'SECUNDARIA' 'D' 'MATUTINA']
['4TO' 'SECUNDARIA' 'A' 'MATUTINA']
['4TO' 'SECUNDARIA' 'A' 'MATUTINA']
['4TO' 'SECUNDARIA' 'A' 'MATUTINA']
['4TO' 'SECUNDARIA' 'A' 'MATUTINA']
['4TO' 'SECUNDARIA' 'A' 'MATUTINA']
['4TO' 'SECUNDARIA' 'B' 'MATUTINA']
['4TO' 'SECUNDARIA' 'C' 'MATUTINA']
['4TO' 'SECUNDARIA' 'C' 'MATUTINA']
['4TO' 'SECUNDARIA' 'D' 'MATUTINA']
['4TO' 'SECUNDARIA' 'D' 'MATUTINA']
['5TO' 'SECUNDARIA' 'C' 'MATUTINA']
['6TO' 'SECUNDARIA' 'A' 'MATUTINA']
['PP' 'INICIAL' 'A' 'MATUTINA']
['PP' 'INICIAL' 'B' 'MATUTINA']
['1RO' 'PRIMARIA' 'A' 'JEE']
['1RO' 'PRIMARIA' 'B' 'JEE']
['1RO' 'PRIMARIA' 'D' 'JEE']
['1RO' 'PRIMARIA' 'D' 'JEE']
['1RO' 'PRIMARIA' 'D' 'JEE']
['1RO' 'PRIMARIA' 'D' 'JEE']
['1RO' 'PRIMARIA' 'E' 'JEE']
['1RO' 'PRIMARIA' 'E' 'JEE']
['1RO' 'PRIMARIA' 'E' 'JEE']
['1RO' 'PRIMARIA' 'E' 'JEE']
['1RO' 'PRIMARIA' 'E' 'JEE']
['1RO' 'PRIMARIA' 'E' 'JEE']
['1RO' 'PRIMARIA' 'F' 'JEE']
['1RO' 'PRIMARIA' 'F' 'JEE']
['1RO' 'PRIMARIA' 'F' 'JEE']
['1RO' 'PRIMARIA' 'F' 'JEE']
['1RO' 'PRIMARIA' 'F' 'JEE']
['1RO' 'PRIMARIA' 'F' 'JEE']
['1RO' 'PRIMARIA' 'F' 'JEE']
['1RO' 'PRIMARIA' 'F' 'JEE']
['1RO' 'PRIMARIA' 'G' 'JEE']
['1RO' 'PRIMARIA' 'G' 'JEE']
['1RO' 'PRIMARIA' 'G' 'JEE']
['1RO' 'PRIMARIA' 'G' 'JEE']
['1RO' 'PRIMARIA' 'G' 'JEE']
['1RO' 'PRIMARIA' 'G' 'JEE']
['2DO' 'PRIMARIA' 'A' 'JEE']
['2DO' 'PRIMARIA' 'A' 'JEE']
['2DO' 'PRIMARIA' 'A' 'JEE']
['2DO' 'PRIMARIA' 'A' 'JEE']
['2DO' 'PRIMARIA' 'A' 'JEE']
['2DO' 'PRIMARIA' 'A' 'JEE']
['2DO' 'PRIMARIA' 'A' 'JEE']
['2DO' 'PRIMARIA' 'A' 'JEE']
['2DO' 'PRIMARIA' 'A' 'JEE']
['2DO' 'PRIMARIA' 'B' 'JEE']
['2DO' 'PRIMARIA' 'D' 'JEE']
['2DO' 'PRIMARIA' 'D' 'JEE']
['2DO' 'PRIMARIA' 'D' 'JEE']
['2DO' 'PRIMARIA' 'E' 'JEE']
['2DO' 'PRIMARIA' 'F' 'JEE']
['2DO' 'PRIMARIA' 'G' 'JEE']
['2DO' 'PRIMARIA' 'G' 'JEE']
['2DO' 'PRIMARIA' 'G' 'JEE']
['2DO' 'PRIMARIA' 'G' 'JEE']
['2DO' 'PRIMARIA' 'G' 'JEE']
['2DO' 'PRIMARIA' 'G' 'JEE']
['2DO' 'PRIMARIA' 'G' 'JEE']
['2DO' 'PRIMARIA' 'G' 'JEE']
['2DO' 'PRIMARIA' 'G' 'JEE']
['2DO' 'PRIMARIA' 'G' 'JEE']
['3RO' 'PRIMARIA' 'A' 'JEE']
['3RO' 'PRIMARIA' 'B' 'JEE']
['3RO' 'PRIMARIA' 'B' 'JEE']
['3RO' 'PRIMARIA' 'B' 'JEE']
['3RO' 'PRIMARIA' 'B' 'JEE']
['3RO' 'PRIMARIA' 'C' 'JEE']
['3RO' 'PRIMARIA' 'C' 'JEE']
['3RO' 'PRIMARIA' 'D' 'JEE']
['3RO' 'PRIMARIA' 'E' 'JEE']
['3RO' 'PRIMARIA' 'E' 'JEE']
['3RO' 'PRIMARIA' 'E' 'JEE']
['3RO' 'PRIMARIA' 'F' 'JEE']
['3RO' 'PRIMARIA' 'F' 'JEE']
['3RO' 'PRIMARIA' 'F' 'JEE']
['3RO' 'PRIMARIA' 'F' 'JEE']
['3RO' 'PRIMARIA' 'F' 'JEE']
['3RO' 'PRIMARIA' 'F' 'JEE']
['3RO' 'PRIMARIA' 'F' 'JEE']
['3RO' 'PRIMARIA' 'F' 'JEE']
['3RO' 'PRIMARIA' 'F' 'JEE']
['3RO' 'PRIMARIA' 'F' 'JEE']
['3RO' 'PRIMARIA' 'F' 'JEE']
['3RO' 'PRIMARIA' 'F' 'JEE']
['3RO' 'PRIMARIA' 'G' 'JEE']
['3RO' 'PRIMARIA' 'G' 'JEE']
['4TO' 'PRIMARIA' 'A' 'JEE']
['4TO' 'PRIMARIA' 'A' 'JEE']
['4TO' 'PRIMARIA' 'B' 'JEE']
['4TO' 'PRIMARIA' 'C' 'JEE']
['4TO' 'PRIMARIA' 'C' 'JEE']
['4TO' 'PRIMARIA' 'C' 'JEE']
['4TO' 'PRIMARIA' 'D' 'JEE']
['4TO' 'PRIMARIA' 'D' 'JEE']
['4TO' 'PRIMARIA' 'D' 'JEE']
['4TO' 'PRIMARIA' 'D' 'JEE']
['4TO' 'PRIMARIA' 'D' 'JEE']
['4TO' 'PRIMARIA' 'E' 'JEE']
['4TO' 'PRIMARIA' 'E' 'JEE']

In [83]:
merged =pd.merge(data, cursos, how = 'left', left_on=['CURSO', 'CICLO', 'SECCION ', 'TANDA'], right_on=['Grado', 'Nivel', 'Seccion', 'Tanda'])

In [84]:
merged = merged.dropna()

In [44]:
merged.columns

Index(['NO. PEDIDO', 'FECHA', 'ESCUELA', 'TANDA', 'CICLO', 'NOMBRE COMPLETO',
       'SIZE', 'CANT', 'CURSO', 'SECCION ', 'PRECIO', 'PAGO',
       'id_grado_seccion', 'Grado', 'Nivel', 'Seccion', 'Tanda'],
      dtype='object')

In [85]:
merged = merged[['NO. PEDIDO','NOMBRE COMPLETO', 'FECHA','id_grado_seccion','SIZE', 'CANT']]

In [86]:
merged.columns = ('id_pedido','nombre_Estudiante' ,'fecha_venta','id_grado_seccion', 'size', 'cantidad')

In [49]:
merged.iloc[:,:-2].to_csv('ventas.csv')

In [51]:
pedidos = data[['NO. PEDIDO','FECHA','ESCUELA']]

In [52]:
pedidos.columns = ('id_pedido','fecha_inicio', 'id_escuela')

In [53]:
pedidos =pedidos.drop_duplicates()

     id_pedido fecha_inicio             id_escuela
0          1.0    9/27/2021    SAN VICENTE DE PAUL
33         1.0    9/30/2021    SAN VICENTE DE PAUL
40         1.0    9/22/2021    SAN VICENTE DE PAUL
218        2.0    10/4/2021      COLOMBINA CANARIO
248        3.0    10/4/2021      COLOMBINA CANARIO
270        4.0    10/7/2021           URSULA REYES
370        5.0    10/8/2021    SAN VICENTE DE PAUL
519        6.0    10/8/2021  LILIA PORTALATIN SOSA
520        6.0   10/10/2021  LILIA PORTALATIN SOSA
667        7.0    10/8/2021      COLOMBINA CANARIO
693        8.0   10/12/2021          LAS MALVINAS
838        9.0   10/12/2021          LAS MALVINAS

In [67]:
import datetime as dt
pedidos = pedidos.loc[[40,218,248,270,370,519,667,693,838]]
pedidos['fecha_inicio'] = pedidos.fecha_inicio.astype('datetime64')
pedidos['fecha_fin'] = pedidos.fecha_inicio + dt.timedelta(days=15)

In [71]:

pedidos['id_escuela'] = (4,7,7,5,4,6,7,8,8)

In [74]:
pedidos.iloc[:,1:].to_csv('pedidos_.csv')

In [69]:
escuela = pd.read_csv('escuela.csv')

In [70]:
escuela, (4,7,7,5,4,6,7,8,8)

   id_escuela                nombre          director
0           1             Juan Bosh  Ciudad juan bosh
1           2  Cristobalina Batista           Herrera
2           4           SAN VICENTE          los mina
3           5          URSULA REYES           barrio1
4           6      LILIA PORTALATIN           barrio1
5           7     COLOMBINA CANARIO           barrio1
6           8          LAS MALVINAS           barrio1

In [76]:
pedidos

     id_pedido fecha_inicio  id_escuela  fecha_fin
40         1.0   2021-09-22           4 2021-10-07
218        2.0   2021-10-04           7 2021-10-19
248        3.0   2021-10-04           7 2021-10-19
270        4.0   2021-10-07           5 2021-10-22
370        5.0   2021-10-08           4 2021-10-23
519        6.0   2021-10-08           6 2021-10-23
667        7.0   2021-10-08           7 2021-10-23
693        8.0   2021-10-12           8 2021-10-27
838        9.0   2021-10-12           8 2021-10-27

In [93]:

merged['id_pedido'] = merged.id_pedido + 1

In [91]:
merged.loc[merged.id_pedido == 9.0,'id_pedido'] = 8

In [95]:
merged.iloc[:,:-3].to_csv('ventas.csv')

In [100]:
merged

,id_pedido,nombre_Estudiante,fecha_venta,id_grado_seccion,size,cantidad,id_pediddo
0,2.0,JONAS GUZMAN,9/27/2021,4.0,10,1.0,NaN
1,2.0,SCARLET JIMENEZ,9/27/2021,4.0,M,1.0,NaN
2,2.0,MICHAEL ABREU,9/27/2021,34.0,14,1.0,NaN
3,2.0,MARCO GARCIA,9/27/2021,49.0,14,1.0,NaN
4,2.0,JESUS GIL,9/27/2021,49.0,14,1.0,NaN
...,...,...,...,...,...,...,...
915,9.0,MIRANDA (PROF.CLARA),10/12/2021,31.0,8,1.0,8.0
916,9.0,JUAN JOSE,10/12/2021,31.0,10,2.0,8.0
917,9.0,CAMILA,10/12/2021,31.0,10,1.0,8.0
918,9.0,FRANYELIS,10/12/2021,31.0,10,1.0,8.0
919,9.0,PROF PP C,10/12/2021,31.0,L,1.0,8.0

In [117]:
ventas_id = pd.read_csv('venta_id.csv')
ventas_id

     id_venta                nombre  id_pedido       fecha  id_grado_seccion
0           1        ELizabeth Pena          1   1/18/2023               214
1           2        Jose Rodriguez          1   1/18/2023               229
2           3          JONAS GUZMAN          2   9/27/2021                 4
3           4       SCARLET JIMENEZ          2   9/27/2021                 4
4           5         MICHAEL ABREU          2   9/27/2021                34
..        ...                   ...        ...         ...               ...
916       917  MIRANDA (PROF.CLARA)          9  10/12/2021                31
917       918             JUAN JOSE          9  10/12/2021                31
918       919                CAMILA          9  10/12/2021                31
919       920             FRANYELIS          9  10/12/2021                31
920       921             PROF PP C          9  10/12/2021                31

[921 rows x 5 columns]

In [102]:
venta_detalle = pd.merge(merged, size, how='left', on='size')

In [105]:
catalogo = venta_detalle['id_size'].drop_duplicates()
catalogo = pd.DataFrame(catalogo)
catalogo['precio'] = 350
catalogo['id_catalgo'] = 1
catalogo['id_producto'] = 3
catalogo['precio_combo'] = 300
catalogo['comision'] = 50
catalogo

    id_size  precio  id_catalgo  id_producto  precio_combo  comision
0         5     350           1            3           300        50
1        10     350           1            3           300        50
2         7     350           1            3           300        50
5         3     350           1            3           300        50
6         4     350           1            3           300        50
7         6     350           1            3           300        50
12       12     350           1            3           300        50
14        9     350           1            3           300        50
17        8     350           1            3           300        50
29       11     350           1            3           300        50
41        2     350           1            3           300        50

In [106]:
catalogo.to_csv('detalle_cat_1.csv')

In [110]:
det_cat = pd.read_csv("detalle catalogo.csv")
det_cat = det_cat[['id_det', 'id_size']]

In [115]:
venta_detalle = pd.merge(venta_detalle, det_cat, how='left', on= 'id_size')
venta_detalle

,id_pedido,nombre_Estudiante,fecha_venta,id_grado_seccion,size,cantidad,id_pediddo,id_size,id_det
0,2.0,JONAS GUZMAN,9/27/2021,4.0,10,1.0,NaN,5,13
1,2.0,SCARLET JIMENEZ,9/27/2021,4.0,M,1.0,NaN,10,14
2,2.0,MICHAEL ABREU,9/27/2021,34.0,14,1.0,NaN,7,15
3,2.0,MARCO GARCIA,9/27/2021,49.0,14,1.0,NaN,7,15
4,2.0,JESUS GIL,9/27/2021,49.0,14,1.0,NaN,7,15
...,...,...,...,...,...,...,...,...,...
914,9.0,MIRANDA (PROF.CLARA),10/12/2021,31.0,8,1.0,8.0,4,17
915,9.0,JUAN JOSE,10/12/2021,31.0,10,2.0,8.0,5,13
916,9.0,CAMILA,10/12/2021,31.0,10,1.0,8.0,5,13
917,9.0,FRANYELIS,10/12/2021,31.0,10,1.0,8.0,5,13
918,9.0,PROF PP C,10/12/2021,31.0,L,1.0,8.0,11,22

In [120]:
detalle_venta = pd.merge(venta_detalle ,ventas_id, how='inner',left_on=['id_pedido','nombre_Estudiante', 'fecha_venta', 'id_grado_seccion']
,right_on=['id_pedido','nombre', 'fecha', 'id_grado_seccion'] )

In [123]:
detalle_venta = detalle_venta[['id_venta', 'id_det', 'size', 'cantidad', 'fecha']]
detalle_venta['precio'] = 350

C:\Users\jomatos\AppData\Local\Temp\ipykernel_14184\3426045669.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  detalle_venta['precio'] = 350

In [125]:
detalle_venta.to_csv('detalle_venta_add.csv')